version: "3.9"

services:
  mhcheck:
    # image: ghcr.io/mhprodev/mhcheck:latest
    build: .
    container_name: mhcheck
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json
      - ./files:/app/files
     
    
    
