version: "3.9"

services:
  mhcheck:
    # image: ghcr.io/mhprodev/mhcheck:latest
    build: .
    container_name: mhcheck
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json
      - ./files:/app/files

  dashboard:
    build: .
    container_name: mhcheck-dashboard
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - ./config.json:/app/config.json
      - ./files:/app/files
    restart: unless-stopped
